- .github/workflows/continuous-integration.yml
github action to run flake8, pytest, and mypy.
> github action: continuous integration

- demes/__init__.py
- demes/demes.py
- tests/test_demes.py
- tests/test_incremental_build.py
This should allow for incremental builds of a demography. There are some simple tests, but more complex tests might reveal bugs that need to be fixed or features that need to be tweaked.
> closes #25 and #26

- demes/demes.py
- tests/test_demes.py
I've separated this out from the other pr (#28), so we can consider the semantics in isolation.
> Add DemeGraph.in_generations(), which converts to units of generations.

- .github/workflows/continuous-integration.yml
- demes/convert/README
- demes/convert/__init__.py
- demes/convert/msprime_.py
- demes/convert/stdpopsim_.py
- demes/demes.py
- demes/examples.py
- demes/script.py
- docs/convert.rst
- docs/index.rst
- requirements.txt
- setup.cfg
- tests/test_convert.py
- tests/test_incremental_build.py
I expect demes->msprime will be one of the shortest export functions we have. I didn't really test this, other than eyballing the demography debugger output below. So, use at your own risk!
```
$ python demes2msprime.py ../examples/gutenkunst_ooa.yml
Model =  hudson(reference_size=1)
===============================
Epoch: 0 -- 21200.0 generations
===============================
start     end      growth_rate |     0        1        2        3        4        5
-------- --------       -------- | -------- -------- -------- -------- -------- --------
0 | 7.3e+03  7.3e+03              0 |     0        0        0        0        0        0
1 |1.23e+04 1.23e+04              0 |     0        0        0        0        0        0
2 | 2.1e+03  2.1e+03              0 |     0        0        0 …
```
> Add to/from msprime/stdpopsim conversion functions.

- demes/__main__.py
- setup.cfg
> add CLI to validate yaml files

- .github/workflows/lint.yml
- .github/workflows/tests.yml
- docs/conf.py
- requirements.txt
- setup.cfg
* Check formatting with black.
* Separate the workflows into tests and lint. The latter only needs to
run once, whereas the former is run on multiple platforms.
> Github workflow cleanups.

- docs/examples.rst
- docs/index.rst
- docs/installation.rst
- docs/introduction.rst
- docs/tutorial.rst
- docs/tutorial_examples/browning_america.yml
- docs/tutorial_examples/isolation_with_migration.yml
- docs/tutorial_examples/minimal.yml
- docs/tutorial_examples/one_pop_epochs.yml
Work in progress - adding to documentation (introduction, installation, tutorials, etc).
> Filling in documentation

- demes/convert/__init__.py
- demes/convert/moments_.py
- demes/demes.py
- docs/convert.rst
- requirements.txt
- setup.cfg
- tests/test_moments.py
Getting this up here, though not quite finished. I think I've got it working with pure split/branch demographies, but haven't implemented merger/admixture/pulse events yet.
One thing that is confusing me, that you might be able to help with @grahamgower, is I've tried to alter to `__init__.py` in the `demes/convert` directory to import the moments conversion methods. But I get import errors (`ModuleNotFoundError: No module named 'demes.convert.moments_'`). Do I also need to change something somewhere else, maybe in the setup.cfg or similar? It's been stumping me...
> To moments

- demes/demes.py
- tests/test_demes.py
Fill in tests of deme and deme graph validity. Fixed a few minor bugs along the way.
Closes #68
> Increase test coverage

- README.md
- docs/gallery.rst
- docs/index.rst
- docs/installation.rst
- docs/introduction.rst
- docs/tutorial.rst
- docs/tutorial_examples/isolation_with_migration.yml
- docs/tutorial_examples/two_epoch.yaml
Formatting and typo fixes, add section on time conventions.
> clean up tutorial and gallery docs

- .github/workflows/lint.yml
- .gitignore
- demes/__init__.py
- demes/convert/__init__.py
- docs/conf.py
- docs/development.rst
- pyproject.toml
- setup.cfg
- setup.py
> add __version__ attribute to the package

- demes/demes.py
- demes/examples.py
- demes/schema.py
- demes/script.py
- tests/test_demes.py
> remove default_Ne

- demes/convert/moments_.py
- demes/demes.py
- docs/api.rst
- tests/test_demes.py
- tests/test_incremental_build.py
> use keyword args almost everywhere

- demes/demes.py
- tests/test_demes.py
> warn about possibly unexpected model interpretation

- demes/__init__.py
- demes/convert/msprime_.py
- demes/convert/stdpopsim_.py
- demes/demes.py
- demes/load_dump.py
- docs/api.rst
- docs/tutorial.rst
- tests/test_convert.py
- tests/test_demes.py
- tests/test_load_dump.py
- tests/test_moments.py
And some related language cleanups.
Closes #113.
> Rename DemeGraph to Graph.

- demes/demes.py
- demes/load_dump.py
- tests/test_demes.py
- tests/test_load_dump.py
> remove Graph.asdict_compact()

- examples/cloning_example.yml
- tests/test_demes.py
> Bump up test coverage.

- demes/demes.py
- demes/load_dump.py
- examples/bottleneck.yml
- examples/zigzag.yml
- tests/test_demes.py
- tests/test_load_dump.py
This reintroduces `asdict_simplified()` using Graham's start at reformatting it. It also tries to address some of the issues from #58 - flexible specification, but "canonical" simplified output.
Would love suggestions here
> Add asdict_simplified

- demes/demes.py
- tests/test_demes.py
I don't know if I've made this overly complicated, but the algorithm here in the `simplify_migration_rates()` function in `asdict_simplified()` iteratively searches for sets of n-way symmetric migrations within a given migration rate attribute set (rate, start_time, end_time), in a way that hopefully catches all n-way symmetric migrations, starting with those that include larger sets of demes.
It needs some more testing, but there are a few simple test scenarios in `test_demes.py`.
> Merge n-way symmetric migrations

- demes/demes.py
- requirements.txt
- tests/__init__.py
- tests/test_demes.py
- tests/test_load_dump.py
And fix a bunch of the fallout.
Closes #24.
Closes #136.
> Add hypothesis strategy for generating a Graph.

- demes/load_dump.py
- examples/browning_america.yml
- examples/cloning_example.yml
- examples/gutenkunst_ooa.yml
- examples/jacobs_papuans.yml
- examples/offshoots.yml
- examples/selfing_example.yml
- tests/test_load_dump.py
> use lists instead of comma-separated fields

- demes/convert/msprime_.py
- demes/demes.py
- requirements.txt
- setup.cfg
- tests/test_demes.py
- tests/test_load_dump.py
> type validation and int/float serialisation

- setup.cfg
- tests/test_load_dump.py
Tests were then checked with successively older versions of ruamel.yaml.
Closes #162.
Closes #163.
> test for well-formed YAML output

- demes/demes.py
- tests/__init__.py
- tests/test_demes.py
Checks non-overlap of migration start/end times if they involve the same source/dest. Am I missing any cases here?
> Closes #166

- demes/convert/moments_.py
- demes/convert/msprime_.py
- demes/demes.py
- docs/api.rst
- docs/tutorial.rst
- docs/tutorial_examples/browning_america.yml
- docs/tutorial_examples/isolation_with_migration.yml
- docs/tutorial_examples/minimal.yml
- docs/tutorial_examples/one_pop_epochs.yml
- examples/bottleneck.yml
- examples/browning_america.yml
- examples/cloning_example.yml
- examples/gutenkunst_ooa.yml
- examples/jacobs_papuans.yml
- examples/linear_growth.yml
- examples/offshoots.yml
- examples/selfing_example.yml
- examples/zigzag.yml
- schema/graph.json
- tests/__init__.py
- tests/test_demes.py
- tests/test_load_dump.py
- tests/test_moments.py
See https://github.com/popsim-consortium/demes-spec/issues/30
> rename initial_size/final_size to start_size/end_size

- demes/convert/moments_.py
- demes/convert/msprime_.py
- demes/demes.py
- docs/api.rst
- docs/tutorial.rst
- docs/tutorial_examples/browning_america.yml
- docs/tutorial_examples/isolation_with_migration.yml
- docs/tutorial_examples/minimal.yml
- docs/tutorial_examples/one_pop_epochs.yml
- examples/bottleneck.yml
- examples/browning_america.yml
- examples/cloning_example.yml
- examples/gutenkunst_ooa.yml
- examples/jacobs_papuans.yml
- examples/linear_growth.yml
- examples/offshoots.yml
- examples/selfing_example.yml
- examples/zigzag.yml
- schema/graph.json
- tests/__init__.py
- tests/test_demes.py
- tests/test_load_dump.py
- tests/test_moments.py
> Make Graph.description optional.

- .github/workflows/docs.yml
> Change predicate so that steps run when merging.

- demes/demes.py
- examples/bottleneck.yml
- tests/test_demes.py
- tests/test_load_dump.py
> Enforce root deme start times are inf.

- demes/__init__.py
- demes/convert/msprime_.py
- demes/demes.py
- docs/api.rst
- docs/development.rst
- examples/browning_america.yml
- examples/cloning_example.yml
- examples/gutenkunst_ooa.yml
- examples/jacobs_papuans.yml
- examples/offshoots.yml
- examples/selfing_example.yml
- setup.cfg
- tests/__init__.py
- tests/test_demes.py
- tests/test_load_dump.py
Initial sketch of a possible Builder/Factory-style API, as suggested in #208. The code here is just for discussion and has not been tested. But I think the `Builder` class is fairly complete, and we can offload most of the error checking to the `resolve()` stage. I'm luke-warm on the DemeProxy helper class. Thoughts?
> Add Builder API.

- .github/workflows/tests.yml
> Upload coverage report to codecov.

- demes/demes.py
- tests/test_demes.py
> Fix Graph.assert_close() for pathological migration lists.

- tests/__init__.py
Check that time intervals are wide enough to draw floating
point numbers for the relevant events.
Closes #220.
> Fix hypothesis strategy. Again.

- demes/demes.py
- tests/test_demes.py
The tests here also uncovered a small issue with migration defaults.
If the migration default in question is "demes", then the user must
override to obtain an asymmetric migration. Similarly, if the default is
the "source" and/or "dest", these must be overriden to obtain a
symmetric migration. With the changes here, overrides of 'None' can now
be used with the Builder API.
Closes #214.
> Fix defaults when using Builder, and add more tests.

- CHANGELOG.rst
- demes/demes.py
- docs/conf.py
- requirements.txt
- tests/test_demes.py
Also fixes ``Deme.assert_close()`` to check the ``start_time``.
Closes #224.
> Fix Graph.in_generations() to convert the deme start_time.

- .github/workflows/docs.yml
> Fetch all tags/branches when building docs.

- demes/convert/msprime_.py
I think this is right now. This stuff all needs updating for msprime 1.0 anyway...
> Fix migration.end_time in convert.from_msprime.

- demes/convert/msprime_.py
- demes/convert/stdpopsim_.py
- demes/demes.py
- docs/quickstart.rst
- examples/bottleneck.yml
- examples/browning_america.yml
- examples/cloning_example.yml
- examples/gutenkunst_ooa.yml
- examples/jacobs_papuans.yml
- examples/linear_growth.yml
- examples/offshoots.yml
- examples/selfing_example.yml
- examples/two_epoch.yml
- examples/zigzag.yml
- tests/__init__.py
- tests/test_demes.py
- tests/test_load_dump.py
See https://github.com/popsim-consortium/demes-spec/issues/59
> Rename deme.id to deme.name.

- demes/demes.py
- tests/test_demes.py
> Check pulse time edge cases.

- demes/demes.py
- tests/__init__.py
- tests/test_demes.py
* Check for invalid fields before parsing valid fields.
* Check for multiple pulses causing ancestry proportion > 1.
* Check selfing_rate + cloning_rate <= 1.
Closes #245.
Closes #250.
Closes #242.
> fix three recent issues

- examples/jacobs_papuans.yml
Follows from #241. Also synch with the file in the spec repo.
> Fix Jacobs et al. model.

- demes/__init__.py
- demes/ms.py
- docs/Makefile
- docs/api.md
- tests/ms_asymmetric_migration.sh
- tests/test_convert.py
- tests/test_ms.py
Very much a WIP, but I thought I'd share just so you know I'm working on it at least!
The basic approach of adapting the msprime argparse code will work I think, and I think the error handling for parsing is working well - setting ``parser.error = ValueError`` seems to do the trick quite nicely.
One high level question though: what should we do with ms command line args that aren't to do with directly defining the demography? There's two classes I think:
1. Arguments for defining the sample size. This is intrinsically linked up with defining the demography, so I'm currently returning a tuple ``DemeGraph, num_samples``, so that we return the parsed-out number of samples per deme. I'm not at all sure this is the right approach - maybe we should just ignore all the sample size stuff?
2. What …
> Initial ms parser

- demes/demes.py
- tests/test_demes.py
> Fix in_generations() with time_units=generations and generation_time.

- demes/demes.py
- tests/test_demes.py
> Change to slotted classes.

- demes/hypothesis_strategies.py
Failing example here: https://github.com/grahamgower/demes-c/pull/4/checks?check_run_id=2585463011
> Ensure max_value can be exactly represented as a float32.

- .pre-commit-config.yaml
- README.md
- docs/build.sh
- docs/development.md
- docs/release.md
- examples/zigzag.yml
> Add pre-commit config file and dev instructions.

- demes/__init__.py
- demes/__main__.py
- demes/demes.py
- demes/ms.py
- docs/api.md
- tests/test_cli.py
- tests/test_ms.py
- verification.py
Closes #74.
---
The tests here are somewhat circular, but I think this is as good as its going to get without actually running `ms`. And while I don't want to run `ms` in the CI tests, we almost certainly need to have some checks that do that.
Anyway, my brain hurts. So I'm stopping here.
> add to_ms()

- demes/demes.py
- setup.cfg
- tests/test_demes.py
> Add toplevel metadata.

- demes/load_dump.py
- tests/test_demes.py
> Check for "Infinity" strings in load_all().

- .github/workflows/docs.yaml
- README.md
> Use 'latest' symlink for docs.

- .github/workflows/docs.yaml
---
```
t490:g $ mkdir main
t490:g $ ln -sf main latest
t490:g $ ls -lR
.:
total 0
lrwxrwxrwx 1 grg grg  4 Dec  7 20:11 latest -> main/
drwxr-xr-x 2 grg grg 40 Dec  7 20:11 main/
./main:
total 0
```
```
t490:g $ ln -sf main latest
t490:g $ ls -lR
.:
total 0
lrwxrwxrwx 1 grg grg  4 Dec  7 20:11 latest -> main/
drwxr-xr-x 2 grg grg 60 Dec  7 20:11 main/
./main:
total 0
lrwxrwxrwx 1 grg grg 4 Dec  7 20:11 main -> main
```
```
t490:g $ rm -fr *
t490:g $ mkdir main
t490:g $ ln -sfT main latest
t490:g $ ln -sfT main latest
t490:g $ ln -sfT main latest
t490:g $ ls -lR
.:
total 0
lrwxrwxrwx 1 grg grg  4 Dec  7 20:12 latest -> main/
drwxr-xr-x 2 grg grg 40 Dec  7 20:12 main/
./main:
total 0
```
> Fix 'latest' symlink.

- demes/demes.py
- tests/test_demes.py
> Permit selfing_rate + cloning_rate >=1.

- demes/demes.py
- tests/test_demes.py
> Fix deme.size_at(deme.start_time).

- .github/workflows/dev.yaml
- .github/workflows/docs.yaml
- .github/workflows/lint.yaml
- .github/workflows/tests.yaml
- .github/workflows/wheel.yaml
- .pre-commit-config.yaml
- demes/ms.py
- docs/development.md
- requirements/docs.txt
- requirements/lint.txt
- requirements/tests.txt
- setup.cfg
> Bump dependencies; drop Python 3.6.

- .github/workflows/tests.yaml
- .gitmodules
- demes/demes.py
- demes/load_dump.py
- examples/browning_america.yaml
- examples/zigzag.yaml
- tests/test_demes.py
- tests/test_ms.py
- tests/test_spec.py
> Test the demes-python implementation against the spec.

- demes/__main__.py
- demes/demes.py
- demes/load_dump.py
- demes/ms.py
- docs/api.md
- docs/introduction.md
- docs/quickstart.md
This shifts the language to better reflect the language
in the spec, with respect to the HDM, MDM, model resolution,
and model validation.
Closes #326.
Closes #327.
> Docs edit pass

- demes/__main__.py
- demes/ms.py
- docs/cli.md
> Ms converted models have diploid population sizes.

- CITATION.md
- docs/CITATION.md
- docs/_toc.yml
> Add CITATION.md
