demes/demes.py, demes/examples.py, demes/script.py, examples/bottleneck.yml, examples/browning_america.yml, examples/gutenkunst_ooa.yml, examples/linear_growth.yml, examples/offshoots.yml, examples/roundtrips.py, examples/selfing_example.yml, examples/zigzag.yml, tests/test_demes.py
This is a start for changing the flow of time to forward instead of backward, and adding some vocabulary for the different demographic events, such as splits, branches, mergers, and admixtures, as proposed in #7. There is still quite a bit to play around with here, but I wanted to get at least an unpolished PR up with some of those ideas so there's a reference for discussion. I'll fill it out a bit more tomorrow as well.
=> Start features for forward time

demes/examples.py
Closes #41 
I didn't do a full audit of all models, but did check that we weren't erroneously rescaling the migration rate. Only found an issue with the OOA model.
=> remove scaling by generation time of migration rates

demes/demes.py, tests/test_demes.py
We don't currently check that migrations and pulses occur only at times that both demes involved exist. This just ensures that migration epochs don't extend outside the time intervals of demes involved, and pulse times occur when both demes are present as well.
Now if there is an invalid migration or pulse event, we raise a ValueError.
=> Migration validity checks

demes/convert/msprime_.py, demes/demes.py, tests/test_convert.py, tests/test_demes.py
Part of #68.
I've made a decision about equality semantics here. Some attributes of the deme graph are just used as defaults for setting attributes on added demes (`default_Ne`, `selfing_rate`, `cloning_rate`), and I consider this a model implementation detail. So here we only check if the demes in the graphs compare equal, rather than caring about the values of these convenience attributes.
=> add equality tests

demes/demes.py, demes/schema.py, demes/script.py, docs/api.rst, docs/conf.py, docs/index.rst, docs/schema.rst, examples/gutenkunst_ooa.yml, requirements.txt
This adds some quickstart/examples at the top of the API page (using jupyter-sphinx). It moves the yaml schema to its own file to facilitate verbatim inclusion in the docs. The format of the schema isn't ideal for readers, but I didn't want to just duplicate it in a different format either. Maybe we could autogenerate something from this which is formatted more neatly?
=> update and rearrange API docs

demes/convert/msprime_.py, demes/demes.py, tests/test_demes.py
And some somewhat related cleanups:
* disallow duplicate ids in ancestors lists,
* require that an ancestor is in the graph already,
* and check the start_time of a deme intersects with
the ancestors' existence intervals.
Closes #90.
=> disallow duplicate deme ids in a graph

demes/convert/moments_.py, demes/demes.py, demes/script.py, tests/test_demes.py, tests/test_incremental_build.py, tests/test_moments.py
Addresses #96, #97. The `split`, `merge`, etc functions in the `DemeGraph` class now are underscored. `get_demographic_events()` has been changed to `list_demographic_events()` and returns a dictionary of lists of discrete demographic events.
Is there a better name for `list_demographic_events` or is that fine?
=> Remove demographic event attributes

demes/__init__.py, demes/load_dump.py
load_asdict() allows a user to programmatically modify the model before
it gets built into a graph with demes.Graph.fromdict(). This facilitates
easy construction of parameterised models.
Closes #63.
=> add load_asdict() to load YAML/JSON as dict

requirements.txt, schema/graph.json, setup.cfg, tests/test_demes.py
I haven't added all of the constraints. This is because some constraints are rather complicated (we need initial_size, but this can be definied directly for the deme, or instead in the epoch(s)) or impossible to define with a JSON schema (e.g. sum of proportions must be 1).
=> add JSON schema for a demes graph

demes/demes.py, tests/test_demes.py
Solves #111.
I have add the return of newly created objects in :
- `Graph.deme` returns `Deme` object,
- `Graph.migration` returns `Migration` object,
- `Graph.pulse` returns `Pulse` object,
- `Graph.symmetric_migration` returns list of `Migration` objects.
Also I have put simple type checks in tests: `TestGraph.test_newly_created_objects_return` function.
[UPDATE] I have also changed type of Graph._deme_map from `Mapping` to `Dict` as there was an error from mypy that Mapping is not mutable and it is updated in `Graph.deme` method. I have found that the [best solution](https://stackoverflow.com/questions/60456140/unsupported-target-for-indexed-assignment-with-mypy-depending-on-type-hinting) is TypedDict but it is available since python3.8 only.
=> Return newly created objects in Graph methods

demes/demes.py
I have put doc string in ``demes`` for each ``isclose`` method (Issue #77 ) and create new option ``raise_ex`` for them that indicates if Exception should be raised with information about what is not close in objects (Issue #115 ).
Option ``raise`` is not available so I choose ``raise_ex`` if there are any other suggestions then I will fix the name.
Also check out the documentation - it is very similar, but maybe there will be suggestions too.
I have not finished tests for ``raise_ex``. I will finish them after some feedback.
=> Add documentation and option for raising exceptions in isclose methods

demes/convert/msprime_.py, demes/convert/stdpopsim_.py, demes/load_dump.py
This avoids using the pyyaml-style dump(), which outputs truly
horrific YAML by default. The new API has its quirks though,
and we need to set some undocumented flags for it to behave.
Closes #155.
---
E.g. new output from `python demes/convert/stdpopsim_.py HomSap OutOfAfrica_3G09`. [EDIT: I found the undocumented flag to maintain dict-insertion-order sorting]
```yaml
description: The three population Out-of-Africa model from Gutenkunst et al. 2009.
It describes the ancestral human population in Africa, the out of Africa event,
and the subsequent European-Asian population split. Model parameters are the maximum
likelihood values of the various parameters given in Table 1 of Gutenkunst et al.
time_units: generations
doi:
- https://doi.org/10.1371/journal.pgen.1000695
demes:
- id: YRI …
```
=> use new ruamel API for dump()

demes/load_dump.py, tests/test_load_dump.py
Also make the loads()/dumps() functions wrap these, instead of
the other way around.
Closes #153.
Closes #154.
=> change load()/dump() to accept streams

demes/demes.py, tests/test_demes.py
Previous behavior was that if a deme had a single epoch, start/end times and sizes were dropped down to the deme level. This retains all epochs instead.
=> Simplified dict retains epochs

demes/convert/moments_.py, demes/convert/msprime_.py, demes/demes.py, docs/api.rst, docs/tutorial_examples/browning_america.yml, docs/tutorial_examples/isolation_with_migration.yml, docs/tutorial_examples/minimal.yml, examples/browning_america.yml, examples/cloning_example.yml, examples/gutenkunst_ooa.yml, examples/jacobs_papuans.yml, examples/offshoots.yml, examples/selfing_example.yml, requirements.txt, tests/test_demes.py, tests/test_load_dump.py, tests/test_moments.py
This takes a stab at a few of the things we've been discussing, including requiring that a non-empty list of `epochs` must be given for each `deme`, and that attributes like `selfing_rate` and `cloning_rate` are given in a dict of `defaults` at the `graph` and `deme` level.
Definitely a work in progress and will need some cleaning up or rethinking perhaps.
=> defaults and defining demes

examples/zigzag.yml
Also changes the (unused) generation time to match Schiffels & Durbin.
Closes #179.
=> Fix Zigzag population sizes.

demes/demes.py, docs/api.rst, tests/test_demes.py
* Successors and predecessors are now functions, rather than properties.
* list_demographic_events() has been renamed to discrete_demographic_events().
* Tests added for each of the above.
* Split, Branch, Merge, Admix added to docs/api.rst.
Closes #173 #170 #99.
=> successors, predecessors, and discrete demographic events

demes/demes.py, tests/test_demes.py
Closes #244.
Probably needs more tests. I'm also not sure of the best way to avoid hitting this in the hypothesis strategy for generating graphs (but I didn't get any failures yet).
=> Check sum of migration rates entering a deme are <= 1.

CHANGELOG.md, demes/__init__.py, demes/convert/msprime_.py, demes/demes.py, docs/api.md, requirements/docs.txt, tests/__init__.py, tests/test_demes.py
Also restores the migration simplification code that was removed
in commit e2a7e05 (#209).
Closes #263.
=> Resolve symmetric migrations into pairs of asymmetric migrations.

demes/demes.py, demes/load_dump.py
Closes #235.
Closes #291.
Sample output:
```
$ python
Python 3.9.3 (default, Apr  8 2021, 23:35:02)
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import demes
>>> demes.load("examples/gutenkunst_ooa.yml")
description: The Gutenkunst et al. (2009) OOA model.
time_units: years
generation_time: 25
doi: ['https://doi.org/10.1371/journal.pgen.1000695']
demes:
- name: ancestral
description: Equilibrium/root population
epochs:
- {end_time: 220000.0, start_size: 7300}
- name: AMH
description: Anatomically modern humans
ancestors: [ancestral]
epochs:
- {end_time: 140000.0, start_size: 12300}
- name: OOA
description: Bottleneck out-of-Africa population
ancestors: [AMH]
epochs:
- {end_time: 21200.0, start_size: 2100}
- name: YRI
description: Yoruba …
```
=> Output YAML for the Graph __str__.

demes/demes.py, examples/linear_size_function_example.yml, tests/test_demes.py
Solves issue #296.
I have add `linear` as available size function in `demes`. I am not sure about the order of size functions in doc strings and in lists: I have put `linear` at the end as it is less popular than `constant` and `exponential`.
I also have created new example .yml file for demography with several linear size changes in order to check load and dump in tests.
=> Add linear size function support

demes/load_dump.py, tests/test_load_dump.py
This does require explicit conversion of string-valued "Infinity" when
loading the JSON file, but that code is quite modest.
See https://github.com/popsim-consortium/demes-spec/issues/70
=> Stringify infinity in JSON output.

demes/demes.py, tests/test_demes.py
Also make the function generally more useful by returning migration
matrices even when there are no migrations.
=> Fix Graph._migration_matrices() when there's no inf start_time.

demes/demes.py, demes/hypothesis_strategies.py, setup.cfg, tests/__init__.py, tests/test_demes.py
=> Add Deme.size_at() to compute the deme size at a given time.

codecov.yml, demes/hypothesis_strategies.py, tests/conftest.py, tests/test_demes.py, tests/test_load_dump.py
=> Remove unittest in favour of pytest.

demes/__init__.py, demes/demes.py, demes/load_dump.py, docs/api.md, tests/conftest.py, tests/test_load_dump.py
=> Add load_all()/dump_all() to support multidoc YAML.

.github/workflows/tests.yml, demes/__main__.py, demes/load_dump.py, demes/ms.py, docs/_config.yml, docs/_toc.yml, docs/cli.md, requirements/docs.txt, setup.cfg, tests/test_cli.py, tests/test_ms.py
There are a few differences here compared with #338. In particular, the `ms` subcommand is a first class citizen with proper help output (reusing the existing ms parser argparse code, which is somewhere between complicated and impossible when using click). I don't have a strong opinion on what the "validate" subcommand is called, or how the options are spelled, but I think the options/defaults in this PR strike better balance than #338.
```
$ python -m demes -h
usage: __main__.py [-h] {validate,ms} ...
Validate and convert Demes models
positional arguments:
{validate,ms}
validate     Validate a model.
ms           Build a demes model using ms commands.
optional arguments:
-h, --help     show this help message and exit
```
```
$ python -m demes validate -h
usage: __main__.py validate [-h] …
```
=> Add CLI (argparse version).

demes/__init__.py, demes/hypothesis_strategies.py, setup.cfg, tests/test_import_visibility.py
Closes #324.
Note that non-public symbols are still accessible, and that some
applications, such as iPython, will ignore `__all__` when offering
tab-completion suggestions.
=> Use `__all__` to advertise public API.

demes/demes.py, tests/test_demes.py, tests/test_ms.py
=> fix some pulse edge cases

demes/demes.py, tests/test_demes.py
Was a pretty quick bug to find - `dest` repeated twice instead of both `source` and `dest` when checking one end of the migration time interval.
=> Closes #384

demes/demes.py, demes/load_dump.py, tests/test_demes.py
~~Check if "Infinity" is given as a start time, which is converted to `math.inf` in `Builder.add_deme()`. Maybe there is a more appropriate place to handle this?~~ What do you think, @grahamgower 
~~Edit: uses `load_dump._unstringify_infinities()` in `Builder.resolve()`.~~
Edit 2: simply adjust a deme or migration start time in `add_deme()` and `add_migration()`. Using `_unstringify_infinities()` causes some complications where `fromdict()` in `Builder.resolve()` is not able to catch type errors.
=> Closes #358

demes/load_dump.py, tests/test_load_dump.py
This is a flow-control exception rather than an error condition,
and when it appears in backtraces it can be confusing.
---
Compare the error from this yaml file:
```yaml
time_units: generations
demes:
- name: a
epochs:
- start_size: 1
- name: b
epochs:
- start_size: 1
pulses:
- {source: a, dest: b, time: 100, proportion: 0.1}
```
Before this commit:
```
$ demes parse p.yaml
Traceback (most recent call last):
File "/home/grg/.local/lib/python3.9/site-packages/demes/load_dump.py", line 22, in _open_file_polymorph
with open(polymorph, mode) as f:
TypeError: expected str, bytes or os.PathLike object, not TextIOWrapper
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/grg/.local/bin/demes", line 8, in <module>
sys.exit(cli()) …
```
=> Don't yield in an exception handler.

demes/demes.py, demes/ms.py, setup.cfg, tests/test_ms.py
---
I noticed a missing "f" on an f-string and wanted to check for other occurences. It turns out there's a lack of tooling around this (for obvious reasons - there would be lots of false positives). However, there is an [open pr for pylint](https://github.com/PyCQA/pylint/pull/4787) adding checks for this, so I pulled that down and ran it. I checked some other stuff too using pylint, but in general its value seems marginal.
=> Fix some f-strings; additional linting.

.github/workflows/docs.yaml, docs/is_new_stable.py
---
The idea here is that we can link to a 'stable' docs path from external projects (e.g. for the sphinx objects.inv file). I manually created a stable symlink in the current docs repo.
=> Create "stable" symlink for the docs.

docs/quickstart.md, requirements/docs.txt
Replace sphinx-panel with sphinx-design, which was removed in
jupyter-book 0.13.0
=> Bump jupyter-book

.gitignore, demes/demes.py, demes/ms.py, tests/test_demes.py
I encountered a need for this feature when looking to develop a `snakemake` workflow that expected specific deme labels for post-processing of simulations. The method is fairly straightforward and implements the type-checks. I will update the tests for this as well if it is a useful feature for others to have or if alternative spec-checks should be performed.
=> Renaming demes within Graph object

demes/demes.py
=> Handle invalid proportions
